baseURL = "https://1stindependencerealty.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summarylength = 20
[[menu.main]]
name = "The Team"
url = "/teams"
weight = 6
[[menu.main]]
name = "Home Value Request"
parent = "Buyers & Sellers"
url = "https://1stindependencerealty.com/home-value-request"
weight = 3
[[menu.main]]
name = "Advanced Search"
parent = "Property Search"
url = "http://1stindependencerealty.idxhome.com/listing/search/advanced/148201/25?location=Enter+cities+or+zip+codes&propertyType=SFR%2CCND&minListPrice=&maxListPrice=&squareFeet=&bedrooms=0&bathCount=0&_openHomesOnlyYn=on&_dateRange=on&_virtualTourYn=on"
weight = 2
[[menu.main]]
name = "Mortgage Calculator"
parent = "Buyers & Sellers"
url = "https://1stindependencerealty.idxhome.com/mortcalc/148201"
weight = 2
[[menu.main]]
name = "Search"
parent = "Property Search"
url = "https://1stindependencerealty.idxhome.com/homesearch/148201"
weight = 1
[[menu.main]]
name = "Property Organizer"
parent = "Buyers & Sellers"
url = "https://1stindependencerealty.idxhome.com/organizer/login/148201"
weight = 1
[[menu.main]]
name = "Testimonials"
url = "/testimonials"
weight = 5
[[menu.main]]
name = "Featured Listings"
url = "https://1stindependencerealty.idxhome.com/featured/148201"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Property Search"
weight = 3
[[menu.main]]
name = "Buyers & Sellers"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 7
[taxonomies]
category = "categories"
tag = "tags"
