[[redirects]]
  from = "https://anitatherealtor.netlify.app/*"
  to = "https://www.anitatherealtor/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/contact-form"
  to = "/contact"
  status = 301
  force = true #COMMENT: ensure that we always redirect  